//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKairos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int WatchId { get; set; }
        public string Username { get; set; }
        public Nullable<double> Rating { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Watch Watch { get; set; }
    }
}
